# .goreleaser.yml
# Build customization
builds:
  -
    binary: "{{ .ProjectName }}"
    ldflags: -s -w -X main.appName={{ .ProjectName }} -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.appVer={{.Tag}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    darwin: mac
  format: binary
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"